export type SalonExposant2026 = {
  name: string;
  profession: string;
  businessName?: string;
  facebook?: string;
  instagram?: string;
  website?: string;
  imageUrl: string | null;
  conference: boolean;
  atelier: boolean;
};

export const salonExposants2026: SalonExposant2026[] = [
  {
    name: "Alice Laurent",
    profession: "Conseillère et formatrice en huiles essentielles",
    businessName: "Aroma'Life",
    imageUrl: "/images/exposants/2026/alice_laurent.png",
    conference: true,
    atelier: true,
    instagram:"https://www.instagram.com/aromalifeacademie",
  },
  {
    name: "Audrey Le Gall",
    profession: "Atelier arts et bien-être",
    businessName: "Le Cocon Créatif",
    imageUrl: "/images/exposants/2026/audrey_legall.png",
    conference: false,
    atelier: true,
    instagram:"https://www.instagram.com/audrey.artiste.pro",
    facebook:"https://www.facebook.com/coconcreatif",
  },
  {
    name: "Guylène Servant",
    profession: "Coaching intuitif / Techniques de libération des émotions",
    businessName: "Go-Bonheur",
    imageUrl: "/images/exposants/2026/guylene_servant.png",
    conference: false,
    atelier: false,
    facebook:"https://www.facebook.com/profile.php?id=61574621175553",
  },
  {
    name: "Philippe Claër",
    profession: "Magnétiseur",
    imageUrl: "/images/exposants/2026/philippe_clear.png",
    conference: false,
    atelier: false,
  },
  {
    name: "Véronique Vérove",
    profession: "Numérologue — Accompagnement & conseils",
    imageUrl: "/images/exposants/2026/veronique_verove.png",
    conference: true,
    atelier: false,
    instagram:"https://www.instagram.com/veroniqueverove",
    facebook:"https://www.facebook.com/EntreCorpsetConscience",
  },
  {
    name: "Laura Coniasse",
    profession: "Libération des blocages inconscients et émotionnels",
    businessName: "La Voix des Métamorph’OSEs",
    imageUrl: "/images/exposants/2026/laura_coniasse.png",
    conference: true,
    atelier: true,
    instagram:"https://www.instagram.com/lavoixdesmetamorphoses",
    facebook:"https://www.facebook.com/profile.php?id=61567020314678",
  },
  {
    name: "Roseline Perchey",
    profession: "Shiatsu, Massage Tui Na",
    businessName: "Roseline SHIATSU",
    imageUrl: "/images/exposants/2026/roseline_perchey.png",
    conference: false,
    atelier: false,
    website:"https://www.roselineshiatsu43700.com/",
  },
  {
    name: "Joëlle Gire",
    profession: "Créatrice au crochet",
    businessName: "Le crochet de Joëlle",
    imageUrl: "/images/exposants/2026/joelle_gire.png",
    conference: false,
    atelier: true,
    facebook:"https://www.facebook.com/profile.php?id=61589373676126",
  },
  {
    name: "Takako Onodera-Reiss",
    profession: "Créatrice des bijoux en Origami",
    businessName: "Chizoukou",
    imageUrl: "/images/exposants/2026/takako_onodera.png",
    conference: false,
    atelier: true,
    facebook:"https://www.facebook.com/chizoukou/",
    instagram:"https://www.instagram.com/origamicizoukou/",
    website:"https://chizoukou.com/",
  },
  {
    name: "Adeline Roussel-Dussault",
    profession: "Somatopathie",
    imageUrl: "/images/exposants/2026/adeline_roussel-dussault.png",
    conference: false,
    atelier: false,
  },
  {
    name: "Michèle Perron",
    profession: "Bijoux Magnetix",
    businessName: "Magnetix Wellness",
    imageUrl: "/images/exposants/2026/michele_perron.png",
    conference: false,
    atelier: false,
    website: "https://www.vitalixworld.com/fr?ref=micheleperron",
  },
  {
    name: "Ludivine Sciacca",
    profession: "Prothésie ongulaire, nail art",
    businessName: "Lovadia - beauté des ongles",
    imageUrl: "/images/exposants/2026/ludivine_sciacca.png",
    conference: false,
    atelier: false,
    facebook:"https://www.facebook.com/lovadianailart",
    instagram:"https://www.instagram.com/lovadiabeautedesongles",
    website: "https://lovadianailart.com/",
  },
  {
    name: "Coline Gallien",
    profession: "Professeure de Yoga",
    businessName: "Wellness by Coline",
    imageUrl: "/images/exposants/2026/coline_gallien.png",
    conference: false,
    atelier: true,
    facebook:"https://www.facebook.com/profile.php?id=61568697977779",
    instagram:"https://www.instagram.com/wellnessbycoline",
    website: "https://wellnessbycoline.com/",
  },
  {
    name: "Claire Henquet",
    profession: "Autrice- Santé mentale et résilience",
    businessName: "Vous ne guérirez jamais!",
    imageUrl: "/images/exposants/2026/claire_henquet.png",
    conference: true,
    atelier: false,
  },
  {
    name: "Bernard Perron",
    profession: "Arbre de Vie",
    imageUrl: "/images/exposants/2026/bernard_perron.png",
    conference: false,
    atelier: false,
  },
  {
    name: "Bonsaï club du Velay",
    profession: "Club de bonsaï",
    imageUrl: "/images/exposants/2026/bonsaiclubduvelay.png",
    conference: false,
    atelier: false,
    facebook: "https://www.facebook.com/profile.php?id=100011753498270",
  },
  {
    name: "Amélie Lashermes",
    profession: "Fabrication de bougies",
    businessName: "La Fabrique de Winnie",
    imageUrl: "/images/exposants/2026/amelie_lashermes.png",
    conference: false,
    atelier: false,
    website: "https://lafabriquedewinnie.fr/",
  },
  {
    name: "Thomas Ploton",
    profession: "Praticien et coach en alignement émotionnel",
    businessName: "Espace Soreï",
    imageUrl: "/images/exposants/2026/thomas_ploton.png",
    conference: true,
    atelier: false,
    website: "https://thomasploton.fr/",
    facebook: "https://www.facebook.com/p/Espace-Sore%C3%AF-100089542741116/",
    instagram: "https://www.instagram.com/thomasploton",
  },
  {
    name: "Patricia Vezzaro",
    profession: "Shiatsu humain et Animalier",
    imageUrl: "/images/exposants/2026/patricia_vezzaro.png",
    conference: false,
    atelier: true,
    website: "https://www.shiatsuaura.fr/",
    facebook: "https://www.facebook.com/aucoeurdesmains43",
    instagram: "https://www.instagram.com/patricia.shiatsu43",
  },
  {
    name: "Morgan Emica",
    profession: "Clairvoyance accompagnement sur l'identité",
    businessName: "Solaria Alchimia",
    imageUrl: "/images/exposants/2026/morgan_emica.png",
    conference: false,
    atelier: true,
    website: "https://www.solaria-alchimia.fr/",
    facebook: "https://www.facebook.com/profile.php?id=100012004518648",
    instagram: "https://www.instagram.com/solaria.corps.et.conscience/",
  },
  {
    name: "STRADA",
    profession: "Communication & Relations Annonceurs",
    imageUrl: "/images/exposants/2026/strada.png",
    conference: false,
    atelier: false,
    website: "https://www.strada-dici.com/",
    facebook: "https://www.facebook.com/strada.laviedici/",
    instagram: "https://www.instagram.com/stradamagazine/",
  },
  {
    name: "Hervé Blandin",
    profession: "Maison passive en bois et paille",
    businessName: "Association Naturel-home",
    imageUrl: "/images/exposants/2026/herve_blandin.png",
    conference: false,
    atelier: false,
    website: "https://lamaisonpassiveenboisetpaille.over-blog.com/",
  },
  {
    name: "Dany Cless",
    profession: "Artiste peintre",
    imageUrl: "/images/exposants/2026/dany_cless.png",
    conference: false,
    atelier: false,
    instagram: "https://www.instagram.com/danycless/",
  },
  {
    name: "Olivier Rossignol",
    profession: "Accompagnateur énergétique dans l'expression de l'Etre",
    businessName: "Éveil Matriciel",
    imageUrl: "/images/exposants/2026/olivier_rossignol.png",
    conference: false,
    atelier: true,
    facebook: "https://www.facebook.com/profile.php?id=61553761825037",
  },
];
